---
title: "Distributions"
author: "Beniamino Sartini"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
library(solarr)
library(ggplot2)
library(dplyr)
```

## Gumbel 

```{r}
# ============ Setup ============
# Random seed
set.seed(1)
# Grid of points 
x <- seq(-5, 5, 0.01)
# Number of simulations
n <- 1000
scale <- c(0.5, 1, 1.5)
# ===================================
```


### Density 

```{r}
ggplot()+
  geom_line(aes(x, dgumbel(x, scale = scale[1]), color = "plot_1"))+
  geom_line(aes(x, dgumbel(x, scale = scale[2]), color = "plot_2"))+
  geom_line(aes(x, dgumbel(x, scale = scale[3]), color = "plot_3"))+
  labs(x = "x", y = "Density", color = "Scale parameter: ")+
  scale_color_manual(values = c(plot_1 = "red", plot_2 = "black", plot_3 = "blue"),
                     labels = c(plot_1 = scale[1], plot_2 = scale[2], plot_3 = scale[3]))+
  theme_bw()+
  theme(legend.position = "top")
```
### Distribution 

```{r}
ggplot()+
  geom_line(aes(x, pgumbel(x, scale = scale[1]), color = "plot_1"))+
  geom_line(aes(x, pgumbel(x, scale = scale[2]), color = "plot_2"))+
  geom_line(aes(x, pgumbel(x, scale = scale[3]), color = "plot_3"))+
  labs(x = "x", y = "P(X < x)", color = "Scale parameter: ")+
  scale_color_manual(values = c(plot_1 = "red", plot_2 = "black", plot_3 = "blue"),
                     labels = c(plot_1 = scale[1], plot_2 = scale[2], plot_3 = scale[3]))+
  theme_bw()+
  theme(legend.position = "top")
```

### Random generator 

```{r}
# Simulations 
dplyr::bind_rows(
  dplyr::bind_cols(type = "plot_1", t = 1:n, x = rgumbel(n, scale = scale[1])),
  dplyr::bind_cols(type = "plot_2", t = 1:n, x = rgumbel(n, scale = scale[2])),
  dplyr::bind_cols(type = "plot_3", t = 1:n, x = rgumbel(n, scale = scale[3]))
) %>%
  ggplot()+
  geom_line(aes(t, x, color = type))+
  facet_wrap(~type)+
  labs(x = "n", y = "x", color = "Scale parameter: ")+
  scale_color_manual(values = c(plot_1 = "red", plot_2 = "black", plot_3 = "blue"),
                     labels = c(plot_1 = scale[1], plot_2 = scale[2], plot_3 = scale[3]))+
  theme_bw()+
  theme(legend.position = "top")
```

