---
title: "seasonalClearsky"
author: "Beniamino Sartini"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(tidyverse)
library(solarr)
# Model's spec
spec <- solarModel_spec$new()
spec$specification("Oslo")
# Extract data from the specification
data <- spec$data
# GHI time series 
x <- data$GHI
# Sequence of dates 
date <- data$date
# Reference latitude for extraterrestrial radiation  
lat <- spec$coords$lat
# Clear sky time series 
clearsky <- data$clearsky
```

## Inputs 

### Specification: seasonalClearsky_spec()

```{r}
# Specification 
spec_Ct <- seasonalClearsky_spec(method = "CLS", order = 2, order_H0 = 1, method_H0 = "spencer", period = 365, include.intercept = TRUE, include.trend = FALSE)
```

### Control: control_seasonalClearsky()

```{r}
# Control parameters
control <- control_seasonalClearsky(delta0 = 1.4, lower = 0, upper = 3, by = 0.001, ntol = 10, eps = 0.01, lambda = 100, quiet = FALSE)
```

## OLS and delta optimization 

```{r}
# Initialize the model 
clearsky_model_OLS <- seasonalClearsky$new(spec = spec_Ct, control = control)
# Test the function
#self <- clearsky_model$.__enclos_env__$self
#private <- clearsky_model$.__enclos_env__$private
#super <- clearsky_model$.__enclos_env__$super
# Fit the parameters
clearsky_model_OLS$fit(x, date, lat, clearsky)
clearsky_model_OLS
```

```{r}
data$Ct <- clearsky_model_OLS$predict(data$n)

plot_1 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(CAMS = "blue", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_2 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct, color = "Fitted"))+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  scale_color_manual(values = c(Fitted = "red", CAMS = "blue"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_3 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct, color = "Fitted"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(Fitted = "red", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")
gridExtra::grid.arrange(plot_1, plot_2, plot_3, nrow = 1)
```

## RLS and delta optimization 

```{r}
# Initialize the model 
clearsky_model_RLS <- clearsky_optimizer_RLS(clearsky_model_OLS, newdata = data, lambda = control$lambda)
# Test the function
#self <- clearsky_model_RLS$.__enclos_env__$self
#private <- clearsky_model_RLS$.__enclos_env__$private
#super <- clearsky_model_RLS$.__enclos_env__$super
# Fit the parameters
clearsky_model_RLS <- clearsky_optimizer_delta(clearsky_model_RLS, data)
clearsky_model_RLS
```

```{r}
# Extract data from the specification
data$Ct_RLS <- clearsky_model_RLS$predict(data$n)

plot_1 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(CAMS = "blue", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_2 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct_RLS, color = "Fitted"))+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  scale_color_manual(values = c(Fitted = "red", CAMS = "blue"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_3 <- data %>%
#dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct_RLS, color = "Fitted"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(Fitted = "red", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")
gridExtra::grid.arrange(plot_1, plot_2, plot_3, nrow = 1)
```

## CLS 

```{r}
# Initialize the model 
clearsky_model_CLS <- clearsky_optimizer_CLS(clearsky_model_OLS, newdata = data, eps = -0.01)
# Test the function
#self <- clearsky_model_CLS$.__enclos_env__$self
#private <- clearsky_model_CLS$.__enclos_env__$private
#super <- clearsky_model_CLS$.__enclos_env__$super
```

```{r}
# Extract data from the specification
data$Ct_CLS <- clearsky_model_CLS$predict(data$n)

plot_1 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(CAMS = "blue", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_2 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct_CLS, color = "Fitted"))+
  geom_line(aes(n, clearsky, color = "CAMS"))+
  scale_color_manual(values = c(Fitted = "red", CAMS = "blue"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_3 <- data %>%
#dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct_CLS, color = "Fitted"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(Fitted = "red", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")
gridExtra::grid.arrange(plot_1, plot_2, plot_3, nrow = 1)
```

## Comparison 

```{r}
# Extract data from the specification
data$Ct_RLS <- clearsky_model_RLS$predict(data$n)

plot_1 <- data %>%
dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct, color = "OLS"))+
  geom_line(aes(n, Ct_RLS, color = "RLS"))+
  geom_line(aes(n, Ct_CLS, color = "CLS"))+
  
  geom_line(aes(n, clearsky, color = "CAMS"))+
  scale_color_manual(values = c(OLS = "red", RLS = "purple", CLS = "green", CAMS = "blue"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")

plot_2 <- data %>%
#dplyr::filter(date >= "2020-01-01" & date <= "2021-01-01")%>%
  ggplot()+
  geom_line(aes(n, Ct, color = "OLS"))+
  geom_line(aes(n, Ct_RLS, color = "RLS"))+
  geom_line(aes(n, Ct_CLS, color = "CLS"))+
  geom_line(aes(n, GHI, color = "GHI"))+
  scale_color_manual(values = c(OLS = "red", RLS = "purple", CLS = "green", GHI = "black"))+
  labs(color = "", x = "Day of the year", y = "Clear sky")+
  theme_bw()+
  theme(legend.position = "top")
gridExtra::grid.arrange(plot_1, plot_2, nrow = 1)
```


```{r}
# Extract data from the specification
data$Xt_OLS <- 1 - data$GHI / data$Ct
data$Xt_RLS <- 1 - data$GHI / data$Ct_RLS
data$Xt_CLS <- 1 - data$GHI / data$Ct_CLS

fig1 <- ggplot(data)+
  geom_line(aes(n, Xt_OLS, group = Year), alpha = 0.2)
fig2 <- ggplot(data)+
  geom_line(aes(n, Xt_RLS, group = Year), alpha = 0.2)
fig3 <- ggplot(data)+
  geom_line(aes(n, Xt_CLS, group = Year), alpha = 0.2)

gridExtra::grid.arrange(fig1, fig2, fig3, nrow = 3)

 ggplot(data)+
  geom_density(aes(Xt_OLS, color = "OLS"), alpha = 0.2)+
  geom_density(aes(Xt_RLS, color = "RLS"), alpha = 0.2)+
  geom_density(aes(Xt_CLS, color = "CLS"), alpha = 0.2)
```



### Test: imputed outliers 

```{r}
# Impute outliers
data$Ct <- clearsky_model_OLS$predict(data$n)
outliers <- clearsky_outliers(data[["GHI"]], data$Ct, data$date, quiet = TRUE)
data[["GHI"]] <- outliers$x
# Test tolerance parameter
cat(paste0("\033[1;35m---------------\033[0m", "\033[1;32m  Test clearskyModel_control and clearskyModel_fit \033[1;35m---------------\033[0m \n"))
test_msg <- paste0("Check if the number of outliers imputed is below ", control$ntol, "...", "(", outliers$n, ") ",
                   ifelse(outliers$n <= control$ntol, "\033[1;32mPassed\033[0m!\n", "\033[1;31mNOT passed\033[0m! \n\n"))
cat(test_msg)
```

### Test: delta parameter 

```{r}
# Test delta parameter
delta <- clearsky_model_OLS$extra_params$delta / clearsky_model_OLS$control$delta0
test_delta <- delta > control$lower & delta < control$upper
test_msg <- paste0("Check if the parameter delta is inside lower (", control$lower, ") and upper (", control$upper,")",
                   "...", "(", delta, ") ",
                   ifelse(test_delta, "\033[1;32mPassed\033[0m!\n", "\033[1;31mNOT passed\033[0m! \n\n"))
cat(test_msg)
```

### Test: order of seasonal components

```{r}
# Count the number of parameters 
n.params_target <- ifelse(spec_Ct$include.intercept, 1, 0)
n.params_target <- n.params_target + ifelse(spec_Ct$include.trend, 1, 0)
n.params_target <- n.params_target + spec_Ct$order * 2
n.params_target <- n.params_target + spec_Ct$order_H0 
# Test if the number of parameters is correct 
n.params <- length(clearsky_model_OLS$coefficients)
# Print result 
test_msg <- paste0("Check if the number of parameters is equal to ", n.params_target, "...", "(", n.params, ") ",
                   ifelse(n.params == n.params_target, "\033[1;32mPassed\033[0m!\n", "\033[1;31mNOT passed\033[0m! \n\n"))
cat(test_msg)
```

## Differential

Note differential when a trend is true is not implemented

```{r}
dt <- 0.00001
n0 <- 34
(clearsky_model_OLS$predict(n0+dt) - clearsky_model_OLS$predict(n0)) / dt
clearsky_model_OLS$differential(n0)
```

```{r}
dt <- 0.00001
n0 <- 34
(clearsky_model_CLS$predict(n0+dt) - clearsky_model_CLS$predict(n0)) / dt
clearsky_model_CLS$differential(n0)
```
