---
title: "notebook-gaussian-mixture"
author: "Beniamino Sartini"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(tidyverse)
library(solarr)
```

## Inputs 

```{r}
set.seed(1)
n <- 5000
means = c(-4,-1,2,5)
sd = c(1,1,1,1)
p = c(0.17, 0.34, 0.3, 0.19)
```


## Simulated data

```{r}
# Simulated gaussian mixture
gm <- rmixnorm(n, means = means, sd = sd, p = p)
# Plot points divided by group
ggplot()+
  geom_point(data = gm, aes(t, X))+
  geom_point(data = filter(gm, B1 == 1), aes(t, X1), color = "red")+
  geom_point(data = filter(gm, B2 == 1), aes(t, X2), color = "blue")+
  geom_point(data = filter(gm, B3 == 1), aes(t, X3), color = "orange")+
  geom_point(data = filter(gm, B4 == 1), aes(t, X4), color = "green")+
  theme_bw()+
  labs(x = "t", y = "x")
```

## Moments on simulated data 

```{r}
# Moments on simulated data
## Means
tibble(
  e_emp = c(mean(filter(gm, B1==1)$X1), mean(filter(gm, B2==1)$X2), mean(filter(gm, B3==1)$X3), mean(filter(gm, B4==1)$X4)), 
  e_theoric = means,
  sd_emp = c(sd(filter(gm, B1==1)$X1), sd(filter(gm, B2==1)$X2), sd(filter(gm, B3==1)$X3), sd(filter(gm, B4==1)$X4)), 
  sd_theoric = sd,
  p_emp = c(mean(gm$B1 == 1), mean(gm$B2 == 1), mean(gm$B3 == 1), mean(gm$B4 == 1)), 
  p_theoric = p
) %>%
  knitr::kable()
```

## Density plot 

```{r}
# Grid of points
grid <- seq(min(means) + min(means)*sd[which.min(means)], max(means) + max(means)*sd[which.max(means)], 0.01)
# Plot mixture density
ggplot()+
  geom_area(aes(grid, dmixnorm(grid, means, sd, p)), fill = "lightgray")+
  geom_area(aes(grid,  p[1]*dnorm(grid, means[1], sd[1])), fill = "red", color = "black")+
  geom_area(aes(grid,  p[2]*dnorm(grid, means[2], sd[2])), fill = "blue", alpha = 0.5, color = "black")+
  geom_area(aes(grid,  p[3]*dnorm(grid, means[3], sd[3])), fill = "orange",  alpha = 0.5, color = "black")+
  geom_area(aes(grid,  p[4]*dnorm(grid, means[4], sd[4])), fill = "green",  alpha = 0.5, color = "black")+
  geom_line(aes(grid, dmixnorm(grid, means, sd, p)), linewidth = 1.1, color = "black")+
  theme_bw()+
  labs(x = "x", y = "Density")
```

## Distribution plot 

```{r}
# Plot mixture distribution
ggplot()+
  geom_line(aes(grid,  pnorm(grid, means[1], sd[1])), color = "red")+
  geom_line(aes(grid,  pnorm(grid, means[2], sd[2])), color = "blue")+
  geom_line(aes(grid,  pnorm(grid, means[3], sd[3])), color = "orange")+
  geom_line(aes(grid,  pnorm(grid, means[4], sd[4])), color = "green")+
  geom_line(aes(grid, pmixnorm(grid, means, sd, p)), linewidth = 1.2)+
  theme_bw()+
  labs(x = "x", y = "Distribution")
```
