---
title: "solarModel"
author: "Beniamino Sartini"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
library(solarr)
library(ggplot2)
```

# Control 

```{r}
control_model <- control_solarModel(outliers_quantile = 0)
```

# Fit

```{r}
spec <- solarModel_spec("Ferrara", from="2005-01-01", to="2022-01-01", control_model = control_model)
model <- solarModel(spec)
```

# Simulation 

```{r}
scenario <- solarModel_scenario(model, nsim = 1, by = "1 day")
sim <- tidyr::unnest(scenario$sim, cols = "data")
ggplot()+
  geom_line(data = sim, aes(n, GHI), color = "red")+
  geom_line(data = scenario$emp, aes(n, GHI))+
  theme_bw()
```

# Parameters

```{r}
solarModel_parameters(model, as_tibble = TRUE) %>%
  tidyr::gather("parameter", "value")
```

# Log-likelihood

```{r}
solarModel_loglik(model)
purrr::map_dbl(1:12, ~solarModel_loglik(model, nmonths = .x))
```

```{r}
c_moments <- solarModel_moments(model)

c_moments$GHI_up <- model$transform$GHI(model$transform$Yt(c_moments$mu_up, inverse = TRUE), c_moments$Ct)
c_moments$GHI_up_hi <- model$transform$GHI(model$transform$Yt(c_moments$mu_up + c_moments$sd_up, inverse = TRUE), c_moments$Ct)
c_moments$GHI_up_lo <- model$transform$GHI(model$transform$Yt(c_moments$mu_up - c_moments$sd_up, inverse = TRUE), c_moments$Ct)
c_moments[3:368,] %>%
  ggplot()+
  geom_line(aes(date, GHI), color = "black")+
  geom_line(aes(date, GHI_up), color = "green")+
  geom_line(aes(date, GHI_up_hi), color = "red")+
  geom_line(aes(date, GHI_up_lo), color = "red")

c_moments[3:368,] %>%
  ggplot()+
  geom_line(aes(date, mu_up), color = "green")+
  geom_line(aes(date, mu_dw), color = "red")

c_moments[3:368,] %>%
  ggplot()+
  geom_line(aes(date, mu_up), color = "green")+
  geom_line(aes(date, mu_up + 3*sd_up), color = "red")+
  geom_line(aes(date, mu_up - 3*sd_up), color = "red")

c_moments$GHI_dw <- model$transform$GHI(model$transform$Yt(c_moments$mu_dw, inverse = TRUE), c_moments$Ct)
c_moments$GHI_dw_hi <- model$transform$GHI(model$transform$Yt(c_moments$mu_dw + c_moments$sd_dw, inverse = TRUE), c_moments$Ct)
c_moments$GHI_dw_lo <- model$transform$GHI(model$transform$Yt(c_moments$mu_dw - c_moments$sd_dw, inverse = TRUE), c_moments$Ct)

c_moments[3:368,] %>%
  ggplot()+
  geom_line(aes(date, GHI), color = "black")+
  geom_line(aes(date, GHI_dw), color = "green")+
  geom_line(aes(date, GHI_dw_hi), color = "red")+
  geom_line(aes(date, GHI_dw_lo), color = "red")

```

